version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"

  - directory: "/"
    package-ecosystem: "gomod"
    groups:
      aws-sdk-go:
        patterns:
          - "github.com/aws/aws-sdk-go"
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"
      aws-sdk-go-base:
        patterns:
          - "github.com/hashicorp/aws-sdk-go-base/v2"
          - "github.com/hashicorp/aws-sdk-go-base/v2/*"
      terraform-devex:
        patterns:
          - "github.com/hashicorp/terraform-plugin-framework"
          - "github.com/hashicorp/terraform-plugin-framework-timeouts"
          - "github.com/hashicorp/terraform-plugin-framework-validators"
          - "github.com/hashicorp/terraform-plugin-mux"
          - "github.com/hashicorp/terraform-plugin-sdk/v2"
          - "github.com/hashicorp/terraform-plugin-testing"
    ignore:
      # hcl/v2 should only be updated via terraform-plugin-sdk
      - dependency-name: "github.com/hashicorp/hcl/v2"
      # terraform-plugin-go should only be updated via terraform-plugin-framework
      - dependency-name: "github.com/hashicorp/terraform-plugin-go"
      # terraform-plugin-log should only be updated via terraform-plugin-framework
      - dependency-name: "github.com/hashicorp/terraform-plugin-log"
      # go-hclog should only be updated via terraform-plugin-log
      - dependency-name: "github.com/hashicorp/go-hclog"
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
      # TEMPORARY - Remove below once upstream is fixed
      # Ref: https://github.com/aws/aws-sdk-go-v2/issues/2349
      #
      # config and ini have upstream regressions causing valid configurations to break.
      # feature/s3/manager is also ignored as the latest versions have a dependency
      # on broken config versions.
      - dependency-name: "github.com/aws/aws-sdk-go-v2/config"
      - dependency-name: "github.com/aws/aws-sdk-go-v2/internal/ini"
      - dependency-name: "github.com/aws/aws-sdk-go-v2/feature/s3/manager"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30

  - directory: "/.ci/providerlint"
    package-ecosystem: "gomod"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"

  - directory: "/.ci/tools"
    package-ecosystem: "gomod"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"

  - directory: "/skaff"
    package-ecosystem: "gomod"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"

  - directory: "/tools/tfsdk2fw"
    package-ecosystem: "gomod"
    allow:
      - dependency-type: direct
    ignore:
      # terraform-plugin-sdk/v2 should only be updated via terraform-provider-aws
      - dependency-name: "github.com/hashicorp/terraform-plugin-sdk/v2"
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"

  - directory: "/infrastructure/repository"
    package-ecosystem: "terraform"
    schedule:
      interval: "daily"
