dist: xenial
sudo: required
services:
  - docker
language: go

env:
  global:
    - GOFLAGS=-mod=vendor
    - LINUX_BINARY_PATH=${GOPATH}/bin/terraform-provider-aws
    - DARWIN_BINARY_PATH=${GOPATH}/bin/darwin_amd64/terraform-provider-aws
go_import_path: github.com/terraform-providers/terraform-provider-aws

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Code Lint"
      script: make lint
    - go: "1.13.x"
      name: "Code UnitTest"
      script:
        - make test
        - make gencheck
    - go: "1.13.x"
      name: "Dependencies"
      script: make depscheck
    - go: "1.13.x"
      name: "Website"
      script:
        - make docscheck
        - make website-test
        - make website-lint

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

before_deploy:
  - GIT_TAG=$(git describe --tags)
  - GOOS=linux GOARCH=amd64 make build
  - mv ${LINUX_BINARY_PATH} ${LINUX_BINARY_PATH}_${GIT_TAG}
  - zip -j ${LINUX_BINARY_PATH}_${GIT_TAG}_linux_amd64.zip ${LINUX_BINARY_PATH}_${GIT_TAG}
  - GOOS=darwin GOARCH=amd64 make build
  - mv ${DARWIN_BINARY_PATH} ${DARWIN_BINARY_PATH}_${GIT_TAG}
  - zip -j ${DARWIN_BINARY_PATH}_${GIT_TAG}_darwin_amd64.zip ${DARWIN_BINARY_PATH}_${GIT_TAG}

# Deploy only when a tag is created and pushed to the master branch.
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - ${LINUX_BINARY_PATH}_${GIT_TAG}_linux_amd64.zip
    - ${DARWIN_BINARY_PATH}_${GIT_TAG}_darwin_amd64.zip
  skip_cleanup: true
  file_glob: true
  on:
    branch: master
    tags: true
  condition: ${GIT_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]$ AND ${JOB_NAME} = "Code UnitTest"
