# Copyright IBM Corp. 2014, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: Acceptance Test Embedded Configuration Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/acctest-terraform-embedded-lint.yml
      - .ci/.tflint.hcl
      - .ci/scripts/validate-terraform.sh
      - .ci/tools/go.mod
      - go.sum
      - 'internal/service/**/*_test.go'

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - run: cd .ci/tools && go install github.com/katbyte/terrafmt

      - run: |
          find ./internal/service -type f -name '*_test.go' \
            | sort -u \
            | xargs -I {} terrafmt diff --check --fmtcompat {}

  tflint:
    name: Validate Acceptance Test Terraform
    runs-on: custom-ubuntu-22.04-xl
    strategy:
      matrix:
        path: ['[a-f]', '[g-z]']
    env:
      TEST_FILES_PARTITION: '\./internal/service/${{ matrix.path }}.*/.*_test\.go'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        name: Cache plugin dir
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}

      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci/tools && go install github.com/terraform-linters/tflint

      - run: tflint --config .ci/.tflint.hcl --init

      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION }} | wc -l | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION }} \
            | .ci/scripts/validate-terraform.sh
