name: Acceptance Test Embedded Configuration Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/acctest-terraform-embedded-lint.yml
      - .ci/.tflint.hcl
      - .ci/scripts/validate-terraform.sh
      - .ci/tools/go.mod
      - go.sum
      - 'internal/service/**/*_test.go'

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - run: cd .ci/tools && go install github.com/katbyte/terrafmt

      - run: |
          find ./internal/service -type f -name '*_test.go' \
            | sort -u \
            | xargs -I {} terrafmt diff --check --fmtcompat {}

  tflint:
    name: Validate Acceptance Test Terraform
    runs-on: custom-linux-xl
    strategy:
      matrix:
        path: ['[a-f]', '[g-z]']
    env:
      TEST_FILES_PARTITION: '\./internal/service/${{ matrix.path }}.*/.*_test\.go'

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        name: Cache plugin dir
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}

      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci/tools && go install github.com/terraform-linters/tflint

      - run: tflint --config .ci/.tflint.hcl --init

      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION }} | wc -l | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION }} \
            | .ci/scripts/validate-terraform.sh
