on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

name: Add Community Note to Issues and PRs

jobs:
  AddCommunityComment:
    runs-on: ubuntu-latest
    steps:
      - name: Add community note to new Issues
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            # Community Note

            **Voting for Prioritization**

            * Please vote on this issue by adding a üëç [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this request.
            * Please see our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) for information on how we prioritize.
            * Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

            **Volunteering to Work on This Issue**

            * If you are interested in working on this issue, please leave a comment.
            * If this would be your first contribution, please review the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/).

      - name: Add community note to new Pull Requests
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request_target'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Community Note

            **Voting for Prioritization**

            * Please vote on this pull request by adding a üëç [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this pull request.
            * Please see our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) for information on how we prioritize.
            * Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

            **For Submitters**

            * Review the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/) relating to the type of change you are making to ensure all of the necessary steps have been taken.
            * For new resources and data sources, use [skaff](https://hashicorp.github.io/terraform-provider-aws/skaff/) to generate scaffolding with comments detailing common expectations.
            * Whether or not the branch has been rebased will **not** impact prioritization, but doing so is always a welcome surprise.
