on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
name: Add Community Note to Issues and PRs
jobs:
  AddCommunityComment:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/create-or-update-comment@v1
      name: Add community note to new issues
      with:
        issue-number: ${{ github.event.*.number }}
        body: |
          **Community Note**
          * Please vote on this issue by adding a üëç [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
          * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
          * If you are interested in working on this issue or have submitted a pull request, please leave a comment
