# Copyright IBM Corp. 2014, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: Copyright Checks

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths-ignore:
      - .ci/**
      - .github/**
      - .teamcity/**
      - .release/**
      - infrastructure/repository/labels-service.tf

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

jobs:
  copyplop:
    name: headers check
    runs-on: custom-ubuntu-22.04-medium
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - run: go install github.com/YakDriver/copyplop@latest
      - run: copyplop check
      - name: Check for Git Differences
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after adding copyright headers. Run 'copyplop fix' command and commit."; exit 1)
