name: Copyright Checks

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths-ignore:
      - .ci/**
      - .github/**
      - .teamcity/**
      - .release/**
      - infrastructure/repository/labels-service.tf

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

jobs:
  copywrite:
    name: add headers check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - run: .ci/scripts/copyright-check.sh
