name: Copyright Checks

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths-ignore:
      - .ci/**
      - .github/**
      - .teamcity/**
      - .release/**
      - infrastructure/repository/labels-service.tf
      - .goreleaser.yml

jobs:
  go_generate:
    name: add headers check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version-file: go.mod
      # See also: https://github.com/actions/setup-go/issues/54
      - name: go env
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: go install github.com/hashicorp/copywrite@latest
      - run: copywrite headers
      - name: Check for Git Differences
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after adding copyright headers. Run 'copywrite headers' command and commit."; exit 1)
