# Copyright IBM Corp. 2014, 2025
# "SPDX-License-Identifier: MPL-2.0"

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
name: Firewatch
jobs:
  FirewatchJob:
    if: github.repository_owner == 'hashicorp'
    runs-on: ubuntu-latest
    steps:
      - name: Firewatch
        uses: breathingdust/firewatch@57f8dc8ee08fa407de395e64452f3d005b3a9c28 # v2.0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          alert_threshold: 10
          issue_age_months: 3
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
      - name: UploadArtifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: firewatch
          path: firewatch.data
          if-no-files-found: error
          retention-days: 1
