on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
name: Firewatch
jobs:
  FirewatchJob:
    if: github.repository_owner == 'hashicorp'
    runs-on: ubuntu-latest
    steps:
      - name: Firewatch
        uses: breathingdust/firewatch@7d8033475a379d86f7affd1f6a228f3a6e3f7ffb # v2.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          alert_threshold: 10
          issue_age_months: 3
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
      - name: UploadArtifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: firewatch
          path: firewatch.data
          if-no-files-found: error
          retention-days: 1
