on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
name: Firewatch
jobs:
  FirewatchJob:
    if: github.repository_owner == 'hashicorp'
    runs-on: ubuntu-latest
    steps:
      - name: Firewatch
        uses: breathingdust/firewatch@7d8033475a379d86f7affd1f6a228f3a6e3f7ffb # v2.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          alert_threshold: 10
          issue_age_months: 3
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
      - name: UploadArtifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: firewatch
          path: firewatch.data
          if-no-files-found: error
          retention-days: 1
