name: TeamCity Config Generator
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .teamcity/**

jobs:
  validate-teamcity-config:
    name: Validate TeamCity Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: Build TeamCity Configuration
        run: |
          cd .teamcity
          make tools
          make validate
