name: TeamCity Config Generator
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .teamcity/**

jobs:
  validate-teamcity-config:
    name: Validate TeamCity Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: Build TeamCity Configuration
        run: |
          cd .teamcity
          make tools
          make validate
