name: TeamCity Config Generator
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .teamcity/**

jobs:
  validate-teamcity-config:
    name: Validate TeamCity Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      - name: Build TeamCity Configuration
        run: |
          cd .teamcity
          mvn org.jetbrains.teamcity:teamcity-configs-maven-plugin:generate
