name: TeamCity Config Generator
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .teamcity/**

jobs:
  validate-teamcity-config:
    name: Validate TeamCity Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: Build TeamCity Configuration
        run: |
          cd .teamcity
          make tools
          make validate
