name: TeamCity Config Generator
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .teamcity/**

jobs:
  validate-teamcity-config:
    name: Validate TeamCity Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: adopt
          java-version: 17
          cache: maven
      - name: Build TeamCity Configuration
        run: |
          cd .teamcity
          make tools
          make validate
