# Copyright IBM Corp. 2014, 2025
# "SPDX-License-Identifier: MPL-2.0"

name: Generate CHANGELOG
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
jobs:
  GenerateChangelog:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: .ci/tools/go.mod
      - run: cd .ci/tools && go install github.com/hashicorp/go-changelog/cmd/changelog-build
      - run: ./.ci/scripts/generate-changelog.sh
      - run: |
          if [[ `git status --porcelain` ]]; then
            if ${{github.event_name == 'workflow_dispatch'}}; then
              MSG="Update CHANGELOG.md (Manual Trigger)"
            else
              MSG="Update CHANGELOG.md for #${{ github.event.pull_request.number }}"
            fi
            git config --local user.email changelogbot@hashicorp.com
            git config --local user.name changelogbot
            git add CHANGELOG.md
            git commit -m "$MSG"
            git push
          fi
