name: Generate CHANGELOG (Manual)
on:
  workflow_dispatch:
jobs:
  GenerateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: cd tools && go install github.com/hashicorp/go-changelog/cmd/changelog-build
      - run: |
          ./scripts/generate-changelog.sh
          git config --local user.email "changelogbot@hashicorp.com"
          git config --local user.name "changelogbot"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md (Manual Trigger)" 
          git push
