# Continuous integration handling for GoReleaser
name: GoReleaser CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/goreleaser-ci.yml
      - .goreleaser.yml
      - go.sum
      - main.go
      - internal/**
      - names/**
      - skaff/**
      - tools/**

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      goreleaser: ${{ steps.filter.outputs.goreleaser }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            goreleaser:
              - '.github/workflows/goreleaser-ci.yml'
              - '.goreleaser.yml'

  check:
    needs: changes
    if: ${{ needs.changes.outputs.goreleaser == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - name: goreleaser check
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: check

  build-32-bit:
    # Run a single compiler check for 32-bit architecture (FreeBSD/ARM)
    # Ref: https://github.com/hashicorp/terraform-provider-aws/issues/8988
    runs-on: custom-linux-small
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - name: goreleaser build
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: build --config .github/goreleaser-cross-compiler-test.yml --id 32-bit-arch --snapshot
