name: "Process issues Events"

on:
  issues:
    types:
      - assigned
      - closed
      - edited
      - opened
      - labeled

jobs:
  labels:
    name: Labelers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          sparse-checkout: .github

      - name: Apply Service Labels
        if: contains(fromJSON('["opened", "edited"]'), github.event.action)
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-issue-triage.yml
          enable-versioned-regex: 0
          include-title: 1

      - name: Run Community Check
        id: community_check
        uses: ./.github/actions/community_check
        with:
          user_login: ${{ github.event.action == 'assigned' && github.event.assignee.login || github.event.issue.user.login }}
          maintainers: ${{ secrets.MAINTAINERS }}

      - name: Add needs-triage to New Issues
        if: |
          github.event.action == 'opened'
          && steps.community_check.outputs.maintainer == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue edit ${{ github.event.issue.html_url }} --add-label needs-triage

      - name: Add prioritized When Assigned to a Maintainer
        if: |
          github.event.action == 'assigned'
          && steps.community_check.outputs.maintainer == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue edit ${{ github.event.issue.html_url }} --add-label prioritized

      - name: Remove Triage labels on Closure
        if: |
          github.event.action == 'closed'
          && (contains(github.event.issue.labels.*.name, 'needs-triage') || contains(github.event.issue.labels.*.name, 'waiting-response'))
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue edit ${{ github.event.issue.html_url }} --remove-label needs-triage,waiting-response

  project:
    name: Maintainer Work Board
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate GitHub App Token
        id: token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          sparse-checkout: .github/actions/

      - name: Run Community Check
        id: community_check
        if: github.event.action == 'assigned'
        uses: ./.github/actions/community_check
        with:
          user_login: ${{ github.event.assignee.login }}
          maintainers: ${{ secrets.MAINTAINERS }}

      - name: Add Maintainer Assignments
        if: |
          github.event.action == 'assigned'
          && steps.community_check.outputs.maintainer == 'true'
        uses: ./.github/actions/team_working_board
        with:
          github_token: ${{ steps.token.outputs.token }}
          item_url: ${{ github.event.issue.html_url }}
          status: "In Progress"
          view: "working-board"

      - name: Add Issues Labeled prioritized
        if: github.event.label.name == 'prioritized'
        uses: ./.github/actions/team_working_board
        with:
          github_token: ${{ steps.token.outputs.token }}
          item_url: ${{ github.event.issue.html_url }}
          view: "working-board"

      - name: Add Issues Labeled engineering-initiative
        if: github.event.label.name == 'engineering-initiative'
        uses: ./.github/actions/team_working_board
        with:
          github_token: ${{ steps.token.outputs.token }}
          item_url: ${{ github.event.issue.html_url }}
          view: "engineering-initiative"

  community_note:
    name: "Add Community Note"
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "Add community note to new Issues"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            # Community Note

            **Voting for Prioritization**

            * Please vote on this issue by adding a ðŸ‘ [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this request.
            * Please see our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) for information on how we prioritize.
            * Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

            **Volunteering to Work on This Issue**

            * If you are interested in working on this issue, please leave a comment.
            * If this would be your first contribution, please review the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/).

  closed_issue_comment:
    name: "Closed Issue Comment"
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Add comment on closed issues"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            > [!WARNING]
            > This issue has been closed, meaning that any additional comments are hard for our team to see. Please assume that the maintainers will not see them.
            >
            > Ongoing conversations amongst community members are welcome, however, the issue will be locked after 30 days. Moving conversations to another venue, such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), is recommended. If you have additional concerns, please open a new issue, referencing this one where needed.
