name: 'Process issue_comment Events'

on:
  issue_comment:
    types: [created]

jobs:
  community_check:
    name: 'Community Check'
    uses: ./.github/workflows/community-check.yml
    secrets: inherit
    with:
      username: ${{ github.event.comment.user.login }}

  automation_labeler:
    name: 'Automation Labeler'
    needs: community_check
    runs-on: ubuntu-latest
    env:
      # This is a ternary that sets the variable to the assigned user's login on assigned events,
      # and otherwise sets it to the username of the pull request's author. For more information:
      # https://docs.github.com/en/actions/learn-github-actions/expressions#example
      #
      # issue_comment events are triggered by comments on issues and pull requests. Checking the
      # value of github.event.issue.pull_request tells us whether the issue is an issue or is
      # actually a pull request, allowing us to dynamically set the gh subcommand:
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
      COMMAND: ${{ github.event.issue.pull_request && 'pr' || 'issue' }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: 'Remove stale and waiting-response on non-maintainer comment'
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
        run: gh ${{ env.COMMAND }} edit ${{ github.event.issue.html_url }} --remove-label stale,waiting-response
