name: "Process issues Events"

on:
  issues:
    types:
      - assigned
      - closed
      - edited
      - opened
      - labeled

jobs:
  community_check:
    name: "Community Check"
    uses: ./.github/workflows/community-check.yml
    secrets: inherit
    with:
      # This is a ternary that sets the variable to the assigned user's login on assigned events,
      # and otherwise sets it to the username of the pull request's author. For more information:
      # https://docs.github.com/en/actions/learn-github-actions/expressions#example
      username: ${{ github.event.action == 'assigned' && github.event.assignee.login || github.event.issue.user.login }}

  labels:
    name: Labelers
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ github.event.issue.html_url }}
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          sparse-checkout: .github

      - name: Apply Service Labels
        if: contains(fromJSON('["opened", "edited"]'), github.event.action)
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-issue-triage.yml
          enable-versioned-regex: 0
          include-title: 1

      - name: Run Community Check
        id: community_check
        uses: ./.github/actions/community_check
        with:
          user_login: ${{ github.event.action == 'assigned' && github.event.assignee.login || github.event.issue.user.login }}
          maintainers: ${{ secrets.MAINTAINERS }}
          core_contributors: ${{ secrets.CORE_CONTRIBUTORS }}
          partners: ${{ secrets.PARTNERS }}

      - name: Add needs-triage to New Issues
        if: |
          github.event.action == 'opened'
          && steps.community_check.outputs.maintainer == 'false'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --add-label needs-triage

      - name: Add prioritized When Assigned to a Maintainer
        if: |
          github.event.action == 'assigned'
          && steps.community_check.outputs.maintainer == 'true'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --add-label prioritized

      - name: Remove Triage labels on Closure
        if: github.event.action == 'closed'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --remove-label needs-triage,waiting-response

  add_to_project:
    name: "Add to Project"
    runs-on: ubuntu-latest
    needs: community_check
    env:
      # Some gh project calls take the project's ID, some take the project's number
      PROJECT_ID: "PVT_kwDOAAuecM4AF-7h"
      PROJECT_NUMBER: "196"
      STATUS_FIELD_ID: "PVTSSF_lADOAAuecM4AF-7hzgDcsQA"
      VIEW_FIELD_ID: "PVTSSF_lADOAAuecM4AF-7hzgMRB34"
      ITEM_URL: ${{ github.event.issue.html_url }}
    steps:
      - name: "Generate Token"
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: "Assigned to Maintainer"
        if: github.event.action == 'assigned' && needs.community_check.outputs.maintainer == 'true'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          PROJECT_ITEM_ID=$(gh project item-add ${{ env.PROJECT_NUMBER }} --owner "hashicorp" --url ${{ env.ITEM_URL }} --format json | jq '.id')
          gh project item-edit --id "$PROJECT_ITEM_ID" --project-id ${{ env.PROJECT_ID }} --field-id ${{ env.STATUS_FIELD_ID }} --single-select-option-id ${{ vars.team_project_status_in_progress }}
          gh project item-edit --id "$PROJECT_ITEM_ID" --project-id ${{ env.PROJECT_ID }} --field-id ${{ env.VIEW_FIELD_ID }} --single-select-option-id ${{ vars.team_project_view_working_board }}

      - name: "Labeled Prioritized"
        if: github.event.label.name == 'prioritized'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          PROJECT_ITEM_ID=$(gh project item-add ${{ env.PROJECT_NUMBER }} --owner "hashicorp" --url ${{ env.ITEM_URL }} --format json | jq '.id')
          gh project item-edit --id "$PROJECT_ITEM_ID" --project-id ${{ env.PROJECT_ID }} --field-id ${{ env.VIEW_FIELD_ID }} --single-select-option-id ${{ vars.team_project_view_working_board }}

      - name: "Labeled Engineering Initiative"
        if: github.event.label.name == 'engineering-initiative'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          PROJECT_ITEM_ID=$(gh project item-add ${{ env.PROJECT_NUMBER }} --owner "hashicorp" --url ${{ env.ITEM_URL }} --format json | jq '.id')
          gh project item-edit --id "$PROJECT_ITEM_ID" --project-id ${{ env.PROJECT_ID }} --field-id ${{ env.VIEW_FIELD_ID }} --single-select-option-id ${{ vars.team_project_view_engineering_initiative }}

  community_note:
    name: "Add Community Note"
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "Add community note to new Issues"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            # Community Note

            **Voting for Prioritization**

            * Please vote on this issue by adding a ðŸ‘ [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this request.
            * Please see our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) for information on how we prioritize.
            * Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

            **Volunteering to Work on This Issue**

            * If you are interested in working on this issue, please leave a comment.
            * If this would be your first contribution, please review the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/).

  closed_issue_comment:
    name: "Closed Issue Comment"
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Add comment on closed issues"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            > [!WARNING]
            > This issue has been closed, meaning that any additional comments are hard for our team to see. Please assume that the maintainers will not see them.
            >
            > Ongoing conversations amongst community members are welcome, however, the issue will be locked after 30 days. Moving conversations to another venue, such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), is recommended. If you have additional concerns, please open a new issue, referencing this one where needed.
