name: Post Publish

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: "Semver release tag e.g. 1.1.0 (v prefix will be added automatically)"
        required: true

jobs:
  tidy-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Tidy Jira
        uses: breathingdust/github-jira-tidy@2d714f03695734a5721d64f5856e40e260587766 # v0.16.0
        with:
          jira_host: "hashicorp.atlassian.net"
          jira_username: "sdavis3@ibm.com"
          jira_password: ${{ secrets.jira_password }}
          jira_jql_filter: ${{ secrets.jira_jql_filter }}
          jira_github_url_field_id: "Issue Link[URL Field]"
          github_release_name: v${{ github.event.inputs.release_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
