on:
  pull_request_target:
    types: [opened, ready_for_review]
name: Pull Request Project Automation
jobs:
  WorkingBoardReview:
    runs-on: ubuntu-latest
    steps:
    - name: Move team PRs to Review column
      uses: alex-page/github-project-automation-plus@v0.8.1
      if: contains(fromJSON('["anGie44", "breathingdust", "ewbankkit", "gdavison", "maryelizbeth", "YakDriver", "zhelding"]'), github.actor) && github.event.pull_request.draft == false
      with:
        project: AWS Provider Working Board
        column: Open Maintainer PR
        repo-token: ${{ secrets.ORGSCOPED_GITHUB_TOKEN}}
