name: Pull Request Target (All types)

on:
  - pull_request_target

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit
    with:
      username: ${{ github.event.pull_request.user.login }}

  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Apply Labels
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler-pr-triage.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  NeedsTriageLabeler:
    needs: community_check
    name: 'Apply needs-triage to New Pull Requests'
    if: github.event.action == 'opened' && needs.community_check.outputs.maintainer == 'false'
    uses: ./.github/workflows/reusable-add-or-remove-labels.yml
    with:
      add: needs-triage

  PartnerLabeler:
    needs: community_check
    name: 'Apply Partner Label'
    if: github.event.action == 'opened' && needs.community_check.outputs.partner == 'true'
    uses: ./.github/workflows/reusable-add-or-remove-labels.yml
    with:
      add: partner

  SizeLabeler:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Size Label
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '30'
          s_label: 'size/S'
          s_max_size: '60'
          m_label: 'size/M'
          m_max_size: '150'
          l_label: 'size/L'
          l_max_size: '300'
          xl_label: 'size/XL'
          message_if_xl: ''

  PullRequestComments:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to add helpful context for new contributors
        uses: actions/first-interaction@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Welcome @${{github.actor}} :wave:

            It looks like this is your first Pull Request submission to the [Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws)! If you havenâ€™t already done so please make sure you have checked out our [CONTRIBUTOR](https://hashicorp.github.io/terraform-provider-aws/) guide and [FAQ](https://hashicorp.github.io/terraform-provider-aws/faq/) to make sure your contribution is adhering to best practice and has all the necessary elements in place for a successful approval.

            Also take a look at our [FAQ](https://hashicorp.github.io/terraform-provider-aws/faq/) which details how we prioritize Pull Requests for inclusion.

            Thanks again, and welcome to the community! :smiley:
