name: PR triage
on:
  pull_request:
    types: [opened]
jobs:
  markPRsForTriage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
    - name: Apply PR Triage Label
      uses: actions/github@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
      with:
        args: label needs-triage
