# Copyright IBM Corp. 2014, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: Resource Counts
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * WED'
permissions:
  contents: write
  pull-requests: write
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{secrets.APP_PEM }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - run: |
          touch main.tf
          cat << EOF > main.tf
          terraform {
          required_providers {
          aws = {
          source  = "hashicorp/aws"
          }
          }
          }
          EOF
      - run: terraform init
      - run: |
          datasources=$(terraform providers schema -json | jq '.provider_schemas[] .data_source_schemas | length' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
          resources=$(terraform providers schema -json | jq '.provider_schemas[] .resource_schemas | length' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')
          sed -r -i "s/With ([0-9,]+) resources and ([0-9,]+) data sources,/With $resources resources and $datasources data sources,/" website/docs/index.html.markdown
      - run: |
          rm main.tf
          rm .terraform.lock.hcl
          rm -rf .terraform
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: "resource-counts"
          commit-message: "docs: update resource counts"
          title: "docs: update resource counts"
          body: "This PR updates the resource/data source counts included on the provider documentation index page."
