name: tfsdk2fw Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - internal/generate/common/**
      - internal/provider/**
      - tools/tfsdk2fw/**

jobs:
  compile_tfsdk2fw:
    name: Compile tfsdk2fw
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: tools/tfsdk2fw/go.mod
      # See also: https://github.com/actions/setup-go/issues/54
      - name: go env
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-GOCACHE-${{ hashFiles('tools/tfsdk2fw/go.sum') }}-${{ hashFiles('internal/**') }}
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('tools/tfsdk2fw/go.sum') }}
      - name: Try building
        run: |
          cd tools/tfsdk2fw/
          go build -buildvcs=false
